name: Check pull request
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  lint:
    name: "Lint and tets"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Run action
      uses: name212/action-dynamic-uses@dc77a3349fecbd50c85ee651868ac03444af877a # v3
      with:
        uses: 'dir:makefile-go/.github/actions/test'
        checkout_ref: ${{ github.event.pull_request.head.sha }}
        with: |
          run_race_tests: "with_tests"
          parallel_tests: "false"